# Site settings
title: Daeyeol Ryu
email: dy@yoobato.com
description: "Daeyeol's personal web page."
baseurl: ""
url: "" # http://daeyeol.me
github_username:  yoobato

# Build settings
encoding: utf-8
markdown: kramdown
highlighter: rouge

exclude: ["sass", "README.md", "Gemfile", "Gemfile.lock"]
